// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj5eKQSxjuw88rf6cIh1-27hIhv39SaEI',
    appId: '1:966614856030:web:d9fcf8adf1808449f8dfcf',
    messagingSenderId: '966614856030',
    projectId: 'gesture-user-interface',
    authDomain: 'gesture-user-interface.firebaseapp.com',
    storageBucket: 'gesture-user-interface.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbQjcA0XjJZeMG9ssnZQrbHsrbiS53p3E',
    appId: '1:966614856030:android:b3d8df1944e91c52f8dfcf',
    messagingSenderId: '966614856030',
    projectId: 'gesture-user-interface',
    storageBucket: 'gesture-user-interface.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbr-k0s1-78lRjxcQ_YAWpq2XH9DmPx54',
    appId: '1:966614856030:ios:3abde1309191b27df8dfcf',
    messagingSenderId: '966614856030',
    projectId: 'gesture-user-interface',
    storageBucket: 'gesture-user-interface.appspot.com',
    iosClientId: '966614856030-eoldverc4103sfahul5lp1rmorrtdqhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestureUserInterface',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbr-k0s1-78lRjxcQ_YAWpq2XH9DmPx54',
    appId: '1:966614856030:ios:3abde1309191b27df8dfcf',
    messagingSenderId: '966614856030',
    projectId: 'gesture-user-interface',
    storageBucket: 'gesture-user-interface.appspot.com',
    iosClientId: '966614856030-eoldverc4103sfahul5lp1rmorrtdqhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gestureUserInterface',
  );
}
